import "@/app/globals.css";
import Script from "next/script";
import { Inter } from "next/font/google";
import Head from "next/head";
import Header from "@/components/dashboardHeader";
import { SessionProviderHook } from "@/hooks/sessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css"
          rel="stylesheet"
        />
      </Head>
      <body className={inter.className}>
        {/* https://www.youtube.com/watch?v=YCEnpcCYlyo&t=579s midleware */}
        <SessionProviderHook>
          <Header />
          {children}
          <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></Script>
        </SessionProviderHook>
      </body>
    </html>
  );
}
